### ISSUE TITLE
Minimum deployment target iOS 13

### ISSUE THREAD

**Issue by rgustavsson** [CodetrixStudio/CapacitorGoogleAuth#247]
Hello!

You recently bumped the minimum iOS target to 13.0 (pod file) but since your dependency GoogleSignIn has a lower version your plugin fallbacks to 12.0

We happened to upgrade to Cap 4 a couple of weeks ago and now have issues using your plugin (require iOS 13).
Do you have any plans to upgrade to GoogleSignIn 7.0.0? I see they have bumped to iOS 13 in that version.

Many thanks!

**Comment by rgustavsson** [comment]
Solved by https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/251

**Comment by msoler95** [comment]
I updated to the latest version which uses GoogleSignIn 6.2.4 and it's still happening to me. Maybe we need GoogleSignIn 7?
